#!/usr/bin/env bash
# Generated by SonarReviewer (EVA-3). Full scanner log streams live; the
# findings snapshot is teed to the console AND FINDINGS.md. Secrets are
# sourced from outside the repo and never appear in this file.
set -eu -o pipefail
# Self-locating: this committed artifact embeds no machine paths.
tool_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# The key is sanitized/settings-derived, but embed it via one escaped
# assignment anyway \u2014 bash never re-expands a variable's value.
scan_project_key='mobileseal-CED-10-private-photo-vault'
trap 'status=$?; rm -rf '/tmp/evie-sonar-8EuMVc'; if [ "$status" -ne 0 ] && [ ! -f "$tool_dir/.failed" ] && [ ! -f "$tool_dir/.done" ]; then echo "reviewer script exited $status without reporting" > "$tool_dir/.failed"; fi' EXIT
# Ephemeral secrets env in a temp dir OUTSIDE the repo, deleted on exit \u2014
# this absolute path is intentional and NON-REPLAYABLE once the wave ends.
source '/tmp/evie-sonar-8EuMVc/env.sh' || { echo "secrets env missing" > "$tool_dir/.failed"; exit 1; }
repo_root="$(git -C "$tool_dir" rev-parse --show-toplevel 2>/dev/null)" || {
  echo "cannot resolve the checkout: $tool_dir is not inside the reviewed repo" > "$tool_dir/.failed"; exit 1;
}
cd "$repo_root" || { echo "checkout missing: $repo_root" > "$tool_dir/.failed"; exit 1; }
echo "\u2500\u2500 sonarqube reviewer: scanning $(pwd) into $scan_project_key (full log below) \u2500\u2500"
scan_status=0
sonar-scanner '-Dsonar.projectKey=mobileseal-CED-10-private-photo-vault' '-Dsonar.projectName=mobileseal-CED-10-private-photo-vault' '-Dsonar.exclusions=goals/**' '-Dsonar.working.directory=/tmp/evie-sonar-8EuMVc/scannerwork' 2>&1 | tee "$tool_dir/scan.log" || scan_status=$?
if [ "$scan_status" -ne 0 ]; then
  echo "sonar-scanner exited $scan_status (see scan.log)" > "$tool_dir/.failed"
  echo "=== SONARQUBE REVIEWER FAILED (scanner exit $scan_status) ==="
  exit "$scan_status"
fi
# Scanner exit only means the report was UPLOADED \u2014 the server processes it
# in an asynchronous compute task, and querying issues before that task
# completes returns the PREVIOUS analysis (or an empty fresh project): a
# stale verdict that defeats "provably against its own tree". Wait for the
# task the scanner recorded in report-task.txt (EVA-11 gate-wave finding,
# observed live: the wave's fetch returned the prior wave's snapshot).
ce_task_id="$(sed -n 's/^ceTaskId=//p' '/tmp/evie-sonar-8EuMVc/scannerwork/report-task.txt' 2>/dev/null | tr -d '[:space:]' || true)"
if [ -z "$ce_task_id" ]; then
  echo "scanner succeeded but report-task.txt has no ceTaskId \u2014 cannot verify the scan was processed" > "$tool_dir/.failed"
  echo "=== SONARQUBE REVIEWER FAILED (no ceTaskId) ==="
  exit 1
fi
echo
echo "\u2500\u2500 waiting for server-side processing (compute task $ce_task_id) \u2500\u2500"
ce_status=""
for ce_attempt in $(seq 1 90); do
  ce_status="$(curl -sS --fail --max-time 10 -K - <<CFG | bun -e 'const d=JSON.parse(await Bun.stdin.text());console.log(d.task&&d.task.status?d.task.status:"UNKNOWN")'
user = "$SONAR_TOKEN:"
url = "$SONAR_HOST_URL/api/ce/task?id=$ce_task_id"
CFG
)" || ce_status="UNREACHABLE"
  # Pane heartbeat (EVA-16 round-1 cc finding): a silent wait loop past
  # the stall threshold reads as a wedged reviewer.
  echo "ce poll $ce_attempt: $ce_status"
  case "$ce_status" in
    SUCCESS) break ;;
    FAILED|CANCELED)
      echo "sonar compute task $ce_task_id ended $ce_status \u2014 the scan was never processed" > "$tool_dir/.failed"
      echo "=== SONARQUBE REVIEWER FAILED (compute task $ce_status) ==="
      exit 1 ;;
  esac
  sleep 2
done
if [ "$ce_status" != "SUCCESS" ]; then
  echo "sonar compute task $ce_task_id not processed after 90 polls (last status: $ce_status)" > "$tool_dir/.failed"
  echo "=== SONARQUBE REVIEWER FAILED (compute-task wait timed out) ==="
  exit 1
fi
echo "compute task $ce_task_id processed"
echo
echo "\u2500\u2500 open issues (also written to FINDINGS.md) \u2500\u2500"
# Fetched with an explicit status check BEFORE the marker is written \u2014 a
# failed fetch must never produce a "complete" findings file.
issues_status=0
issues="$(curl -sS --fail --max-time 20 -K - <<CFG | bun -e 'const d=JSON.parse(await Bun.stdin.text());if(typeof d.total!=="number"){console.error("unexpected issues payload:",JSON.stringify(d).slice(0,200));process.exit(1)}console.log("total open:",d.total);for(const i of d.issues??[])console.log("-",i.severity,(i.component||"").split(":").pop()+":"+(i.line??"-"),"\u2014",i.message)'
user = "$SONAR_TOKEN:"
url = "$SONAR_HOST_URL/api/issues/search?componentKeys=$scan_project_key&issueStatuses=OPEN&severities=BLOCKER,CRITICAL,MAJOR,MINOR,INFO&ps=500"
CFG
)" || issues_status=$?
if [ "$issues_status" -ne 0 ]; then
  echo "issues fetch failed (exit $issues_status) after a successful scan" > "$tool_dir/.failed"
  echo "=== SONARQUBE REVIEWER FAILED (issues fetch exit $issues_status) ==="
  exit "$issues_status"
fi
{
  echo "# SonarQube findings"
  echo
  echo "Ephemeral project: $scan_project_key (per-branch isolation, EVA-11;"
  echo "deleted at merge cleanup). Scan processed as compute task $ce_task_id."
  echo
  echo "Scope note: this is the OPEN snapshot of that project after scanning"
  echo "this checkout; changed files outside the scan sources are not covered."
  echo
  printf '%s\n' "$issues"
  echo
  echo "REVIEW COMPLETE"
} | tee "$tool_dir/FINDINGS.md"
touch "$tool_dir/.done"
echo "=== SONARQUBE REVIEWER DONE ==="
