#!/usr/bin/env bash
# Generated by CodeRabbitReviewer (EVA-3). CLI progress + findings stream
# live and are teed into FINDINGS.md. Secrets are sourced from outside
# the repo and never appear in this file.
set -eu -o pipefail
# Self-locating: this committed artifact embeds no machine paths.
tool_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
trap 'status=$?; rm -rf '/tmp/evie-coderabbit-m9qgVu'; if [ "$status" -ne 0 ] && [ ! -f "$tool_dir/.failed" ] && [ ! -f "$tool_dir/.done" ]; then echo "reviewer script exited $status without reporting" > "$tool_dir/.failed"; fi' EXIT
# Ephemeral secrets env in a temp dir OUTSIDE the repo, deleted on exit \u2014
# this absolute path is intentional and NON-REPLAYABLE once the wave ends.
source '/tmp/evie-coderabbit-m9qgVu/env.sh' || { echo "secrets env missing" > "$tool_dir/.failed"; exit 1; }
repo_root="$(git -C "$tool_dir" rev-parse --show-toplevel 2>/dev/null)" || {
  echo "cannot resolve the checkout: $tool_dir is not inside the reviewed repo" > "$tool_dir/.failed"; exit 1;
}
cd "$repo_root" || { echo "checkout missing: $repo_root" > "$tool_dir/.failed"; exit 1; }
cr_base='main'
echo "\u2500\u2500 coderabbit reviewer: $(git branch --show-current) vs $cr_base \u2500\u2500"
printf '# CodeRabbit findings\n\n' > "$tool_dir/FINDINGS.md"
cr_status=0
# --api-key comes from the sourced env, never from this committed script.
coderabbit review --api-key "$CODERABBIT_API_KEY" '--plain' '--type' 'committed' '--base' 'main' 2>&1 | tee -a "$tool_dir/FINDINGS.md" || cr_status=$?
if [ "$cr_status" -ne 0 ]; then
  echo "coderabbit review exited $cr_status" > "$tool_dir/.failed"
  echo "=== CODERABBIT REVIEWER FAILED (exit $cr_status) ==="
  exit "$cr_status"
fi
printf '\n%s\n' 'REVIEW COMPLETE' | tee -a "$tool_dir/FINDINGS.md"
touch "$tool_dir/.done"
echo "=== CODERABBIT REVIEWER DONE ==="
